// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Streak struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	CurrentStreak   int64              `json:"current_streak"`
	LongestStreak   int64              `json:"longest_streak"`
	CompletedToday  bool               `json:"completed_today"`
	LastCompletedAt pgtype.Timestamptz `json:"last_completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CategoryID  pgtype.Int8        `json:"category_id"`
	IsCompleted bool               `json:"is_completed"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Uuid         pgtype.UUID        `json:"uuid"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Streaks      int64              `json:"streaks"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
