// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	CompleteTask(ctx context.Context, id int64) (Task, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateStreak(ctx context.Context, userID int64) (Streak, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTask(ctx context.Context, id int64) error
	GetCategoryByID(ctx context.Context, id int64) (Category, error)
	GetStreakByUserID(ctx context.Context, userID int64) (Streak, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListTasksByUser(ctx context.Context, userID int64) ([]Task, error)
	MarkStreakCompletedToday(ctx context.Context, userID int64) (Streak, error)
	ResetDailyCompletionFlags(ctx context.Context) error
	UpdateUserStreaks(ctx context.Context, arg UpdateUserStreaksParams) (User, error)
}

var _ Querier = (*Queries)(nil)
