// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streaks.sql

package sqlcdb

import (
	"context"
)

const createStreak = `-- name: CreateStreak :one
INSERT INTO streaks (user_id, current_streak, longest_streak, completed_today, last_completed_at)
VALUES ($1, 0, 0, FALSE, NULL)
RETURNING id, user_id, current_streak, longest_streak, completed_today, last_completed_at, created_at, updated_at
`

func (q *Queries) CreateStreak(ctx context.Context, userID int64) (Streak, error) {
	row := q.db.QueryRow(ctx, createStreak, userID)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.CompletedToday,
		&i.LastCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStreakByUserID = `-- name: GetStreakByUserID :one
SELECT id, user_id, current_streak, longest_streak, completed_today, last_completed_at, created_at, updated_at
FROM streaks
WHERE user_id = $1
`

func (q *Queries) GetStreakByUserID(ctx context.Context, userID int64) (Streak, error) {
	row := q.db.QueryRow(ctx, getStreakByUserID, userID)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.CompletedToday,
		&i.LastCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markStreakCompletedToday = `-- name: MarkStreakCompletedToday :one
UPDATE streaks
SET completed_today = TRUE,
    last_completed_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, current_streak, longest_streak, completed_today, last_completed_at, created_at, updated_at
`

func (q *Queries) MarkStreakCompletedToday(ctx context.Context, userID int64) (Streak, error) {
	row := q.db.QueryRow(ctx, markStreakCompletedToday, userID)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.CompletedToday,
		&i.LastCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetDailyCompletionFlags = `-- name: ResetDailyCompletionFlags :exec
UPDATE streaks
SET completed_today = FALSE,
    updated_at = NOW()
WHERE completed_today = TRUE
`

func (q *Queries) ResetDailyCompletionFlags(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetDailyCompletionFlags)
	return err
}
